#!/usr/bin/env bash
set -euo pipefail

# Get into the agent-env development environment.  Works from anywhere:
#
#   On the host  → starts the container (if needed) and execs into it
#   In the container → runs directly in ~/work/finfam
#
# Usage:
#   ./dev.sh              # interactive bash shell
#   ./dev.sh npm test     # run a command directly
#   ./dev.sh --recreate   # recreate the container (e.g. after a rebuild)
#   ./dev.sh -d           # start/recreate only, don't exec in (for servers)

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

RECREATE=false
DAEMON=false
ARGS=()
for arg in "$@"; do
    case "$arg" in
        --recreate) RECREATE=true ;;
        -d|--daemon) DAEMON=true ;;
        --*) echo "Unknown option: $arg" >&2; exit 1 ;;
        *) ARGS+=("$arg") ;;
    esac
done

# Default to bash if no command given
if [[ ${#ARGS[@]} -eq 0 ]]; then
    ARGS=(bash)
fi

# Already inside the container — just run in-place
if [[ "${AGENT_ENV:-}" == "1" ]]; then
    cd ~/work/finfam
    exec "${ARGS[@]}"
fi

# On the host — make sure the container is up, then exec in
cd "$SCRIPT_DIR"

# Detect the actual docker socket path (rootless Docker uses a user-scoped socket)
DOCKER_SOCK=""
if [[ -n "${DOCKER_HOST:-}" ]]; then
    DOCKER_SOCK="${DOCKER_HOST#unix://}"
fi
if [[ -z "$DOCKER_SOCK" || ! -S "$DOCKER_SOCK" ]]; then
    for candidate in "/run/user/$(id -u)/docker.sock" /var/run/docker.sock; do
        [[ -S "$candidate" ]] && DOCKER_SOCK="$candidate" && break
    done
fi

# Generate docker-compose.override.yml with conditional mounts.
# Host gitconfig files, ~/work, ~/projects, and docker socket are mounted here.
_override="$SCRIPT_DIR/docker-compose.override.yml"
{
    echo "# Auto-generated by dev.sh — do not edit"
    echo "services:"
    echo "  agent-env:"
    echo "    volumes:"
    # Docker socket — mount to the standard path so docker CLI finds it
    if [[ -n "$DOCKER_SOCK" && -S "$DOCKER_SOCK" ]]; then
        echo "      - ${DOCKER_SOCK}:/var/run/docker.sock"
    fi
    # Mount all ~/.gitconfig* files so includeIf rules and their targets are available
    for f in "$HOME"/.gitconfig*; do
        [[ -f "$f" ]] && echo "      - ${f}:/home/dev/$(basename "$f"):ro"
    done
    # Mount SSH private keys referenced by gitconfig SshCommand directives
    grep -rh -- '-i ' "$HOME"/.gitconfig* 2>/dev/null \
        | sed -n 's/.*-i \([^ "]*\).*/\1/p' \
        | sort -u | while read -r key; do
        key="${key/#\~/$HOME}"
        [[ -f "$key" ]] && echo "      - ${key}:${key/#$HOME//home/dev}:ro"
    done || true
    # Mount ~/work and ~/projects at the HOST path so docker-compose
    # bind-mount paths (resolved via getcwd) match what the host daemon sees.
    # The entrypoint symlinks /home/dev/work → $HOST_HOME/work for convenience.
    [[ -d "$HOME/work" ]]     && echo "      - ${HOME}/work:${HOME}/work"
    [[ -d "$HOME/projects" ]] && echo "      - ${HOME}/projects:${HOME}/projects"
    if [[ -n "${SSH_AUTH_SOCK:-}" ]]; then
        echo "      - ${SSH_AUTH_SOCK}:/tmp/ssh-agent.sock:ro"
        echo "    environment:"
        echo "      - SSH_AUTH_SOCK=/tmp/ssh-agent.sock"
    fi
} > "$_override"

_wait_ready() {
    for _ in $(seq 1 50); do
        docker compose exec agent-env test -f /tmp/.entrypoint-done 2>/dev/null && return 0
        sleep 0.2
    done
    echo "WARNING: entrypoint did not finish in time" >&2
}

if $RECREATE; then
    echo "==> Recreating agent-env container..."
    docker compose up -d --force-recreate
    _wait_ready
elif docker compose ps --status running --format '{{.Name}}' 2>/dev/null | grep -q '^agent-env$'; then
    # Container is running — check if the image is stale
    CONTAINER_IMAGE=$(docker inspect --format '{{.Image}}' agent-env 2>/dev/null || true)
    LATEST_IMAGE=$(docker image inspect --format '{{.Id}}' "$(docker compose config --images 2>/dev/null)" 2>/dev/null || true)
    if [[ -n "$CONTAINER_IMAGE" && -n "$LATEST_IMAGE" && "$CONTAINER_IMAGE" != "$LATEST_IMAGE" ]]; then
        echo "WARNING: the agent-env image was rebuilt, but the container is still running the old image."
        echo "  Run './dev.sh --recreate' to recreate the container with the new image."
        echo "  (Any state not on a persistent volume will be lost.)"
        echo ""
    fi
else
    echo "==> Starting agent-env..."
    docker compose up -d
    _wait_ready
fi

$DAEMON && exit 0
exec docker compose exec -u dev -e USER=dev -w /home/dev/work/finfam agent-env "${ARGS[@]}"
