#!/usr/bin/env bash
set -euo pipefail

# Get into the agent-env development environment.  Works from anywhere:
#
#   On the host  → starts the container (if needed) and execs into it
#   In the container → runs directly in ~/work/finfam
#
# Usage:
#   ./dev.sh              # interactive bash shell
#   ./dev.sh npm test     # run a command directly
#   ./dev.sh --recreate   # recreate the container (e.g. after a rebuild)
#   ./dev.sh -d           # start/recreate only, don't exec in (for servers)
#   ./dev.sh --personal   # mount personal SSH key for personal repo pushes

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

RECREATE=false
DAEMON=false
PERSONAL=false
ARGS=()
for arg in "$@"; do
    case "$arg" in
        --recreate) RECREATE=true ;;
        -d|--daemon) DAEMON=true ;;
        --personal) PERSONAL=true ;;
        --*) echo "Unknown option: $arg" >&2; exit 1 ;;
        *) ARGS+=("$arg") ;;
    esac
done

# Default to bash if no command given
if [[ ${#ARGS[@]} -eq 0 ]]; then
    ARGS=(bash)
fi

# Already inside the container — just run in-place
if [[ "${AGENT_ENV:-}" == "1" ]]; then
    cd ~/work/finfam
    exec "${ARGS[@]}"
fi

# On the host — make sure the container is up, then exec in
cd "$SCRIPT_DIR"

# Detect the actual docker socket path (rootless Docker uses a user-scoped socket)
DOCKER_SOCK=""
if [[ -n "${DOCKER_HOST:-}" ]]; then
    DOCKER_SOCK="${DOCKER_HOST#unix://}"
fi
if [[ -z "$DOCKER_SOCK" || ! -S "$DOCKER_SOCK" ]]; then
    for candidate in "/run/user/$(id -u)/docker.sock" /var/run/docker.sock; do
        [[ -S "$candidate" ]] && DOCKER_SOCK="$candidate" && break
    done
fi

# Generate docker-compose.override.yml with conditional mounts.
# Host gitconfig files, ~/work, ~/projects, ~/hatnote, and docker socket are mounted here.
_override="$SCRIPT_DIR/docker-compose.override.yml"
{
    echo "# Auto-generated by dev.sh — do not edit"
    echo "services:"
    echo "  agent-env:"
    echo "    volumes:"
    # Docker socket — mount to the standard path so docker CLI finds it
    if [[ -n "$DOCKER_SOCK" && -S "$DOCKER_SOCK" ]]; then
        echo "      - ${DOCKER_SOCK}:/var/run/docker.sock"
    fi
    # Mount all ~/.gitconfig* files so includeIf rules and their targets are available
    for f in "$HOME"/.gitconfig*; do
        [[ -f "$f" ]] && echo "      - ${f}:/home/dev/$(basename "$f"):ro"
    done
    # Mount SSH private keys referenced by gitconfig SshCommand directives.
    # Keys are auto-discovered by grepping all ~/.gitconfig* files for '-i <path>'.
    # Both identities (personal + work) must have explicit sshCommand directives
    # so their keys are mounted here. See ~/.gitconfig for the identity map.
    grep -rh -- '-i ' "$HOME"/.gitconfig* 2>/dev/null \
        | sed -n 's/.*-i \([^ "]*\).*/\1/p' \
        | sort -u | while read -r key; do
        key="${key/#\~/$HOME}"
        [[ -f "$key" ]] && echo "      - ${key}:${key/#$HOME//home/dev}:ro"
    done || true
    # Mount ~/work, ~/projects, and ~/hatnote at the HOST path so docker-compose
    # bind-mount paths (resolved via getcwd) match what the host daemon sees.
    # The entrypoint symlinks /home/dev/work → $HOST_HOME/work for convenience.
    [[ -d "$HOME/work" ]]     && echo "      - ${HOME}/work:${HOME}/work"
    [[ -d "$HOME/projects" ]] && echo "      - ${HOME}/projects:${HOME}/projects"
    [[ -d "$HOME/hatnote" ]]   && echo "      - ${HOME}/hatnote:${HOME}/hatnote"
    # Persist ~/.omp (session history, agent DB, logs) on the host so it
    # survives container recreation and is visible to agentsview.
    mkdir -p "$HOME/.omp"
    echo "      - ${HOME}/.omp:/home/dev/.omp"
    if [[ -n "${SSH_AUTH_SOCK:-}" ]]; then
        echo "      - ${SSH_AUTH_SOCK}:/tmp/ssh-agent.sock:ro"
        echo "    environment:"
        echo "      - SSH_AUTH_SOCK=/tmp/ssh-agent.sock"
    fi
} > "$_override"

# Personal mode: ephemeral container with personal SSH key.
# Uses docker compose run (not exec) so the work container is untouched.
if $PERSONAL; then
    _personal_key=""
    for candidate in "$HOME/.ssh/id_ed25519" "$HOME/.ssh/id_ecdsa" "$HOME/.ssh/id_rsa"; do
        [[ -f "$candidate" ]] && _personal_key="$candidate" && break
    done
    if [[ -z "$_personal_key" ]]; then
        echo "ERROR: --personal requires a personal SSH key at ~/.ssh/id_{ed25519,ecdsa,rsa}" >&2
        exit 1
    fi
    _container_key="${_personal_key/#$HOME//home/dev}"

    # SSH config as system-wide include so it works regardless of SSH's ~/ resolution
    # (in rootless Docker, dev is UID 0 and SSH resolves ~ to /root, not /home/dev)
    _ssh_config="$SCRIPT_DIR/.ssh-config-personal"
    cat > "$_ssh_config" <<SSHEOF
Host github.com
    IdentityFile $_container_key
    IdentitiesOnly yes
    StrictHostKeyChecking accept-new
    UserKnownHostsFile /dev/null
SSHEOF
    chmod 644 "$_ssh_config"

    exec docker compose run --rm --no-deps \
        --entrypoint "" \
        --user dev \
        -v "${_personal_key}:${_container_key}:ro" \
        -v "${_ssh_config}:/etc/ssh/ssh_config.d/personal.conf:ro" \
        -e HOME=/home/dev \
        -e USER=dev \
        -w "$HOME/projects" \
        agent-env "${ARGS[@]}"
fi

_wait_ready() {
    for _ in $(seq 1 50); do
        docker compose exec agent-env test -f /tmp/.entrypoint-done 2>/dev/null && return 0
        sleep 0.2
    done
    echo "WARNING: entrypoint did not finish in time" >&2
}

if $RECREATE; then
    echo "==> Recreating agent-env container..."
    docker compose up -d --force-recreate
    _wait_ready
elif docker compose ps --status running --format '{{.Name}}' 2>/dev/null | grep -q '^agent-env$'; then
    # Container is running — check if the image is stale
    CONTAINER_IMAGE=$(docker inspect --format '{{.Image}}' agent-env 2>/dev/null || true)
    LATEST_IMAGE=$(docker image inspect --format '{{.Id}}' "$(docker compose config --images 2>/dev/null)" 2>/dev/null || true)
    if [[ -n "$CONTAINER_IMAGE" && -n "$LATEST_IMAGE" && "$CONTAINER_IMAGE" != "$LATEST_IMAGE" ]]; then
        echo "WARNING: the agent-env image was rebuilt, but the container is still running the old image."
        echo "  Run './dev.sh --recreate' to recreate the container with the new image."
        echo "  (Any state not on a persistent volume will be lost.)"
        echo ""
    fi
else
    echo "==> Starting agent-env..."
    docker compose up -d
    _wait_ready
fi

# Donut Browser MCP bridge (host side)
# Creates Unix socket in shared mount, forwards connections to Donut's localhost port
_donut_sock="$HOME/work/.donut-mcp.sock"
if command -v socat >/dev/null 2>&1; then
  if ! pgrep -f "socat.*donut-mcp.sock" >/dev/null 2>&1; then
    rm -f "$_donut_sock"
    nohup socat UNIX-LISTEN:"$_donut_sock",fork,unlink-early TCP:127.0.0.1:51080 >/dev/null 2>&1 &
    disown
  fi
fi

$DAEMON && exit 0
exec docker compose exec -u dev -e HOME=/home/dev -e USER=dev -w /home/dev/work/finfam agent-env "${ARGS[@]}"
